-- MySQL Script generated by MySQL Workbench
-- Sat Dec 19 02:45:25 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Club`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Club` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Club` (
  `id` INT UNSIGNED NOT NULL,
  `MinNumberP` INT UNSIGNED NULL,
  `MaxNumberP` INT UNSIGNED NULL,
  `ClubName` VARCHAR(45) NULL,
  `ClubBreed` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Dog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Dog` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Dog` (
  `id` INT UNSIGNED NOT NULL,
  `OwnerID` INT UNSIGNED NULL,
  `Name` VARCHAR(45) NULL,
  `Age` INT NULL,
  `Breed` INT NULL,
  `FatherBreed` INT NULL,
  `MotherBreed` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_DogsOwner`
    FOREIGN KEY (`OwnerID`)
    REFERENCES `mydb`.`DogsOwner` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `FK_DogsOwner_idx` ON `mydb`.`Dog` (`OwnerID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`DogsOwner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DogsOwner` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`DogsOwner` (
  `id` INT UNSIGNED NOT NULL,
  `FirstName` VARCHAR(45) NULL,
  `LastName` VARCHAR(45) NULL,
  `ClubID` INT UNSIGNED NULL,
  `ParticipantNumber` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_ClubID`
    FOREIGN KEY (`ClubID`)
    REFERENCES `mydb`.`Club` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `FK_ClubID_idx` ON `mydb`.`DogsOwner` (`ClubID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Exhibition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Exhibition` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Exhibition` (
  `id` INT UNSIGNED NOT NULL,
  `Date` DATE NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`ExhibitionUsedRings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ExhibitionUsedRings` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`ExhibitionUsedRings` (
  `id` INT UNSIGNED NOT NULL,
  `RingID` INT UNSIGNED NOT NULL,
  `ExhibitionID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_RingID`
    FOREIGN KEY (`RingID`)
    REFERENCES `mydb`.`Ring` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ExhibitionID`
    FOREIGN KEY (`ExhibitionID`)
    REFERENCES `mydb`.`Exhibition` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `FK_RingID_idx` ON `mydb`.`ExhibitionUsedRings` (`RingID` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `FK_ExhibitionID_idx` ON `mydb`.`ExhibitionUsedRings` (`ExhibitionID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`ExhibitionWinners`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ExhibitionWinners` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`ExhibitionWinners` (
  `id` INT UNSIGNED NOT NULL,
  `Breed` INT NULL,
  `Medal` INT NULL,
  `DogID` INT UNSIGNED NULL,
  `ExhibitionID` INT UNSIGNED NULL,
  `WinMessage` VARCHAR(1000) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_DogID`
    FOREIGN KEY (`DogID`)
    REFERENCES `mydb`.`Dog` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ExhibitionID`
    FOREIGN KEY (`ExhibitionID`)
    REFERENCES `mydb`.`Exhibition` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `FK_DogID_idx` ON `mydb`.`ExhibitionWinners` (`DogID` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `FK_ExhibitionID_idx` ON `mydb`.`ExhibitionWinners` (`ExhibitionID` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `IND_Breed` ON `mydb`.`ExhibitionWinners` (`Breed` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`ExibitionExperts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ExibitionExperts` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`ExibitionExperts` (
  `id` INT UNSIGNED NOT NULL,
  `ExpertID` INT UNSIGNED NOT NULL,
  `RingID` INT UNSIGNED NOT NULL,
  `ExibitionID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_ExpertID`
    FOREIGN KEY (`ExpertID`)
    REFERENCES `mydb`.`Experts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_RingID`
    FOREIGN KEY (`RingID`)
    REFERENCES `mydb`.`Ring` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ExibitionID`
    FOREIGN KEY (`ExibitionID`)
    REFERENCES `mydb`.`Exhibition` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `FK_ExpertID_idx` ON `mydb`.`ExibitionExperts` (`ExpertID` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `FK_RingID_idx` ON `mydb`.`ExibitionExperts` (`RingID` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `FK_ExibitionID_idx` ON `mydb`.`ExibitionExperts` (`ExibitionID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Experts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Experts` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Experts` (
  `id` INT UNSIGNED NOT NULL,
  `DogsOwnerID` INT UNSIGNED NOT NULL,
  `ExpertBreed` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_DogsOwnerID`
    FOREIGN KEY (`DogsOwnerID`)
    REFERENCES `mydb`.`DogsOwner` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `FK_DogsOwnerID_idx` ON `mydb`.`Experts` (`DogsOwnerID` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `DogsOwnerID_UNIQUE` ON `mydb`.`Experts` (`DogsOwnerID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Ring`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ring` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Ring` (
  `id` INT UNSIGNED NOT NULL,
  `Breed` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Users` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `id` INT NOT NULL,
  `Login` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `IsAdmin` TINYINT NOT NULL,
  `DogsOwnerID` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_DogsOwnerID`
    FOREIGN KEY (`DogsOwnerID`)
    REFERENCES `mydb`.`DogsOwner` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `DogsOwnerID_UNIQUE` ON `mydb`.`Users` (`DogsOwnerID` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
