# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DogsPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DogsPage(object):
    def setupUi(self, DogsPage):
        DogsPage.setObjectName("DogsPage")
        DogsPage.resize(400, 420)
        DogsPage.setWindowTitle("")
        self.verticalLayout = QtWidgets.QVBoxLayout(DogsPage)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(DogsPage)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.DogsListWidget = QtWidgets.QListWidget(DogsPage)
        self.DogsListWidget.setObjectName("DogsListWidget")
        self.verticalLayout.addWidget(self.DogsListWidget)
        self.widget = QtWidgets.QWidget(DogsPage)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.AddDogButton = QtWidgets.QPushButton(self.widget)
        self.AddDogButton.setObjectName("AddDogButton")
        self.horizontalLayout.addWidget(self.AddDogButton)
        self.RemoveDogButton = QtWidgets.QPushButton(self.widget)
        self.RemoveDogButton.setObjectName("RemoveDogButton")
        self.horizontalLayout.addWidget(self.RemoveDogButton)
        self.verticalLayout.addWidget(self.widget)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(DogsPage)
        QtCore.QMetaObject.connectSlotsByName(DogsPage)

    def retranslateUi(self, DogsPage):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("DogsPage", "Мои собаки"))
        self.AddDogButton.setText(_translate("DogsPage", "Добавить"))
        self.RemoveDogButton.setText(_translate("DogsPage", "Удалить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DogsPage = QtWidgets.QWidget()
    ui = Ui_DogsPage()
    ui.setupUi(DogsPage)
    DogsPage.show()
    sys.exit(app.exec_())
