# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ExhibitionWinnersPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ExhibitionWinnerPage(object):
    def setupUi(self, ExhibitionWinnerPage):
        ExhibitionWinnerPage.setObjectName("ExhibitionWinnerPage")
        ExhibitionWinnerPage.resize(400, 300)
        ExhibitionWinnerPage.setWindowTitle("")
        self.verticalLayout = QtWidgets.QVBoxLayout(ExhibitionWinnerPage)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(ExhibitionWinnerPage)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.ExhibitionWinnersListWidget = QtWidgets.QListWidget(ExhibitionWinnerPage)
        self.ExhibitionWinnersListWidget.setObjectName("ExhibitionWinnersListWidget")
        self.verticalLayout.addWidget(self.ExhibitionWinnersListWidget)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(ExhibitionWinnerPage)
        QtCore.QMetaObject.connectSlotsByName(ExhibitionWinnerPage)

    def retranslateUi(self, ExhibitionWinnerPage):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("ExhibitionWinnerPage", "Мои достижения"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ExhibitionWinnerPage = QtWidgets.QWidget()
    ui = Ui_ExhibitionWinnerPage()
    ui.setupUi(ExhibitionWinnerPage)
    ExhibitionWinnerPage.show()
    sys.exit(app.exec_())
