# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UserPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserPage(object):
    def setupUi(self, UserPage):
        UserPage.setObjectName("UserPage")
        UserPage.resize(400, 368)
        UserPage.setWindowTitle("")
        self.verticalLayout = QtWidgets.QVBoxLayout(UserPage)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(UserPage)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.AccountInfo = QtWidgets.QGroupBox(UserPage)
        self.AccountInfo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.AccountInfo.setObjectName("AccountInfo")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.AccountInfo)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.LoginLineEdit = QtWidgets.QLineEdit(self.AccountInfo)
        self.LoginLineEdit.setEnabled(False)
        self.LoginLineEdit.setFrame(True)
        self.LoginLineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.LoginLineEdit.setDragEnabled(False)
        self.LoginLineEdit.setReadOnly(False)
        self.LoginLineEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.LoginLineEdit.setClearButtonEnabled(False)
        self.LoginLineEdit.setObjectName("LoginLineEdit")
        self.verticalLayout_2.addWidget(self.LoginLineEdit)
        self.PasswordLineEdit = QtWidgets.QLineEdit(self.AccountInfo)
        self.PasswordLineEdit.setEnabled(False)
        self.PasswordLineEdit.setObjectName("PasswordLineEdit")
        self.verticalLayout_2.addWidget(self.PasswordLineEdit)
        self.PasswordRepeatLineEdit = QtWidgets.QLineEdit(self.AccountInfo)
        self.PasswordRepeatLineEdit.setEnabled(False)
        self.PasswordRepeatLineEdit.setObjectName("PasswordRepeatLineEdit")
        self.verticalLayout_2.addWidget(self.PasswordRepeatLineEdit)
        self.AccountEditMode = QtWidgets.QPushButton(self.AccountInfo)
        self.AccountEditMode.setObjectName("AccountEditMode")
        self.verticalLayout_2.addWidget(self.AccountEditMode)
        self.Common = QtWidgets.QGroupBox(self.AccountInfo)
        self.Common.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Common.setObjectName("Common")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Common)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.FirstNameLineEdit = QtWidgets.QLineEdit(self.Common)
        self.FirstNameLineEdit.setEnabled(False)
        self.FirstNameLineEdit.setObjectName("FirstNameLineEdit")
        self.verticalLayout_3.addWidget(self.FirstNameLineEdit)
        self.LastNameLineEdit = QtWidgets.QLineEdit(self.Common)
        self.LastNameLineEdit.setEnabled(False)
        self.LastNameLineEdit.setObjectName("LastNameLineEdit")
        self.verticalLayout_3.addWidget(self.LastNameLineEdit)
        self.CommonEdiMode = QtWidgets.QPushButton(self.Common)
        self.CommonEdiMode.setObjectName("CommonEdiMode")
        self.verticalLayout_3.addWidget(self.CommonEdiMode)
        self.IsExpertLabel = QtWidgets.QLabel(self.Common)
        self.IsExpertLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.IsExpertLabel.setObjectName("IsExpertLabel")
        self.verticalLayout_3.addWidget(self.IsExpertLabel)
        self.ExpertBreed = QtWidgets.QLabel(self.Common)
        self.ExpertBreed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ExpertBreed.setObjectName("ExpertBreed")
        self.verticalLayout_3.addWidget(self.ExpertBreed)
        self.verticalLayout_2.addWidget(self.Common)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.AccountInfo)

        self.retranslateUi(UserPage)
        QtCore.QMetaObject.connectSlotsByName(UserPage)

    def retranslateUi(self, UserPage):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("UserPage", "Мой профиль"))
        self.AccountInfo.setTitle(_translate("UserPage", "Аккаунт"))
        self.AccountEditMode.setText(_translate("UserPage", "Изменить"))
        self.Common.setTitle(_translate("UserPage", "Профиль"))
        self.CommonEdiMode.setText(_translate("UserPage", "Изменить"))
        self.IsExpertLabel.setText(_translate("UserPage", "Является экспертом"))
        self.ExpertBreed.setText(_translate("UserPage", "Экспертная порода: "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UserPage = QtWidgets.QWidget()
    ui = Ui_UserPage()
    ui.setupUi(UserPage)
    UserPage.show()
    sys.exit(app.exec_())
