# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DogForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(387, 376)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(Form)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.DogNameLineEdit = QtWidgets.QLineEdit(Form)
        self.DogNameLineEdit.setObjectName("DogNameLineEdit")
        self.verticalLayout.addWidget(self.DogNameLineEdit)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.DogAgeSpinBox = QtWidgets.QSpinBox(Form)
        self.DogAgeSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DogAgeSpinBox.setMaximum(20)
        self.DogAgeSpinBox.setObjectName("DogAgeSpinBox")
        self.verticalLayout.addWidget(self.DogAgeSpinBox)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.DogBreedComboBox = QtWidgets.QComboBox(Form)
        self.DogBreedComboBox.setObjectName("DogBreedComboBox")
        self.verticalLayout.addWidget(self.DogBreedComboBox)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.MotherBreedComboBox = QtWidgets.QComboBox(self.groupBox)
        self.MotherBreedComboBox.setObjectName("MotherBreedComboBox")
        self.verticalLayout_2.addWidget(self.MotherBreedComboBox)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.FatherBreedComboBox = QtWidgets.QComboBox(self.groupBox)
        self.FatherBreedComboBox.setObjectName("FatherBreedComboBox")
        self.verticalLayout_2.addWidget(self.FatherBreedComboBox)
        self.verticalLayout.addWidget(self.groupBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ApplyButton = QtWidgets.QPushButton(Form)
        self.ApplyButton.setObjectName("ApplyButton")
        self.horizontalLayout.addWidget(self.ApplyButton)
        self.CancelButton = QtWidgets.QPushButton(Form)
        self.CancelButton.setObjectName("CancelButton")
        self.horizontalLayout.addWidget(self.CancelButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Кличка"))
        self.label_2.setText(_translate("Form", "Возраст"))
        self.label_3.setText(_translate("Form", "Порода"))
        self.groupBox.setTitle(_translate("Form", "Родословная"))
        self.label_4.setText(_translate("Form", "Порода матери"))
        self.label_5.setText(_translate("Form", "Порода отца"))
        self.ApplyButton.setText(_translate("Form", "Ок"))
        self.CancelButton.setText(_translate("Form", "Отменить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
