# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ExhibitionWinnerForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 185)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.MedalLabel = QtWidgets.QLabel(Form)
        self.MedalLabel.setText("")
        self.MedalLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.MedalLabel.setObjectName("MedalLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.MedalLabel)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.DogLabel = QtWidgets.QLabel(Form)
        self.DogLabel.setText("")
        self.DogLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DogLabel.setObjectName("DogLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.DogLabel)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.BreedLabel = QtWidgets.QLabel(Form)
        self.BreedLabel.setText("")
        self.BreedLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.BreedLabel.setObjectName("BreedLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.BreedLabel)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.ExhibitionLabel = QtWidgets.QLabel(Form)
        self.ExhibitionLabel.setText("")
        self.ExhibitionLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ExhibitionLabel.setObjectName("ExhibitionLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.ExhibitionLabel)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.WinMessageLabel = QtWidgets.QLabel(Form)
        self.WinMessageLabel.setText("")
        self.WinMessageLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.WinMessageLabel.setWordWrap(True)
        self.WinMessageLabel.setObjectName("WinMessageLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.WinMessageLabel)
        self.verticalLayout.addLayout(self.formLayout)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Тип награды"))
        self.label_3.setText(_translate("Form", "Собака"))
        self.label_2.setText(_translate("Form", "Порода"))
        self.label_6.setText(_translate("Form", "Выставка"))
        self.label_4.setText(_translate("Form", "Справка призового места"))
        self.pushButton.setText(_translate("Form", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
