# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ExhibitionsPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(480, 366)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.MyExhibitionsListWidget = QtWidgets.QListWidget(Form)
        self.MyExhibitionsListWidget.setMinimumSize(QtCore.QSize(0, 100))
        self.MyExhibitionsListWidget.setObjectName("MyExhibitionsListWidget")
        self.verticalLayout.addWidget(self.MyExhibitionsListWidget)
        self.RemoveExhibitionButton = QtWidgets.QPushButton(Form)
        self.RemoveExhibitionButton.setDefault(False)
        self.RemoveExhibitionButton.setFlat(False)
        self.RemoveExhibitionButton.setObjectName("RemoveExhibitionButton")
        self.verticalLayout.addWidget(self.RemoveExhibitionButton)
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.AvailablExhibitionsListWidget = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AvailablExhibitionsListWidget.sizePolicy().hasHeightForWidth())
        self.AvailablExhibitionsListWidget.setSizePolicy(sizePolicy)
        self.AvailablExhibitionsListWidget.setMinimumSize(QtCore.QSize(0, 100))
        self.AvailablExhibitionsListWidget.setObjectName("AvailablExhibitionsListWidget")
        self.verticalLayout.addWidget(self.AvailablExhibitionsListWidget)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Мои выставки"))
        self.RemoveExhibitionButton.setText(_translate("Form", "Отказаться от участия"))
        self.label_2.setText(_translate("Form", "Доступные выставки"))
        self.pushButton.setText(_translate("Form", "Принять участие"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
