# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SignInWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.AppName = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.AppName.setFont(font)
        self.AppName.setAlignment(QtCore.Qt.AlignCenter)
        self.AppName.setObjectName("AppName")
        self.verticalLayout.addWidget(self.AppName)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.LoginEditLine = QtWidgets.QLineEdit(Dialog)
        self.LoginEditLine.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LoginEditLine.setObjectName("LoginEditLine")
        self.verticalLayout.addWidget(self.LoginEditLine)
        self.PasswordEditLine = QtWidgets.QLineEdit(Dialog)
        self.PasswordEditLine.setInputMask("")
        self.PasswordEditLine.setText("")
        self.PasswordEditLine.setEchoMode(QtWidgets.QLineEdit.Password)
        self.PasswordEditLine.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PasswordEditLine.setObjectName("PasswordEditLine")
        self.verticalLayout.addWidget(self.PasswordEditLine)
        self.SignInButton = QtWidgets.QPushButton(Dialog)
        self.SignInButton.setObjectName("SignInButton")
        self.verticalLayout.addWidget(self.SignInButton)
        self.SignUpButton = QtWidgets.QPushButton(Dialog)
        self.SignUpButton.setObjectName("SignUpButton")
        self.verticalLayout.addWidget(self.SignUpButton)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.AppName.setText(_translate("Dialog", "Выставки собак"))
        self.LoginEditLine.setPlaceholderText(_translate("Dialog", "Логин"))
        self.PasswordEditLine.setPlaceholderText(_translate("Dialog", "Пароль"))
        self.SignInButton.setText(_translate("Dialog", "Войти"))
        self.SignUpButton.setText(_translate("Dialog", "Регистрация"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
