# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SignUpWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 409)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.AccountInfoBox = QtWidgets.QGroupBox(Dialog)
        self.AccountInfoBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.AccountInfoBox.setObjectName("AccountInfoBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.AccountInfoBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.LoginLineEdit = QtWidgets.QLineEdit(self.AccountInfoBox)
        self.LoginLineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LoginLineEdit.setObjectName("LoginLineEdit")
        self.verticalLayout_2.addWidget(self.LoginLineEdit)
        self.PasswordLineEdit = QtWidgets.QLineEdit(self.AccountInfoBox)
        self.PasswordLineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PasswordLineEdit.setObjectName("PasswordLineEdit")
        self.verticalLayout_2.addWidget(self.PasswordLineEdit)
        self.RepeatPasswordLineEdit = QtWidgets.QLineEdit(self.AccountInfoBox)
        self.RepeatPasswordLineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.RepeatPasswordLineEdit.setObjectName("RepeatPasswordLineEdit")
        self.verticalLayout_2.addWidget(self.RepeatPasswordLineEdit)
        self.verticalLayout.addWidget(self.AccountInfoBox)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_3.addWidget(self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_3.addWidget(self.lineEdit_4)
        self.verticalLayout.addWidget(self.groupBox)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem2)
        self.SignUpButton = QtWidgets.QPushButton(Dialog)
        self.SignUpButton.setObjectName("SignUpButton")
        self.verticalLayout.addWidget(self.SignUpButton)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Регистрация"))
        self.AccountInfoBox.setTitle(_translate("Dialog", "Аккаунт"))
        self.LoginLineEdit.setPlaceholderText(_translate("Dialog", "Логин"))
        self.PasswordLineEdit.setPlaceholderText(_translate("Dialog", "Пароль"))
        self.RepeatPasswordLineEdit.setPlaceholderText(_translate("Dialog", "Повторите пароль"))
        self.groupBox.setTitle(_translate("Dialog", "Профиль"))
        self.lineEdit_3.setPlaceholderText(_translate("Dialog", "Фамилия"))
        self.lineEdit_4.setPlaceholderText(_translate("Dialog", "Имя"))
        self.SignUpButton.setText(_translate("Dialog", "Зарегистрироваться"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
